dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install bash
  - sudo chsh -s /bin/bash
  - pip install tox-travis

script:
  - tox
